export const pitchers = [
{
   id: "017",
   first: "Donovan",
   last: "Goodman",
   name: "Donovan Goodman",
   number: 17,
   tier: 1,
   team:"LHV",
   fatigue: 99,
   used:0,
   ability:"rerollOne",
   desc:"Reroll one die. Limit once per inning."
},
{
   id: "018",
   first: "Richie",
   last: "Weaver",
   name: "Richie Weaver",
   number: 18,
   tier: 1,
   team:"SLS",
   fatigue: 99,
   used:0,
   ability: "rerollOne",
   desc: "Reroll one die. Limit once per inning."
},
{
   id: "027",
   first: "Deandre",
   last: "Johnson",
   name: "Deandre Johnson",
   number: 27,
   tier: 2,
   team: "MIL",
   fatigue: 3,
   used:0,
   ability: "rerollSet",
   desc:"Reroll any subset of dice."
},
{
   id: "028",
   first: "Malik",
   last: "Clarke",
   name: "Malik Clarke",
   number: 28,
   tier: 2,
   team: "PIT",
   fatigue: 2,
   used:0,
   ability:"adjustOne",
   desc:"Adjust one die up or down by one." 
},
{
   id: "029",
   first: "Billy",
   last: "Barrett",
   name: "Billy Barrett",
   number: 29,
   tier: 2,
   team: "KC",
   fatigue: 4,
   used:2,
   ability:"addD6",
   desc:"Add one die to the opponent's pool, then remove one die before resolving the inning."
},
{
   id: "030",
   first: "Lamar",
   last: "White",
   name: "Lamar White",
   number: 30,
   tier: 2,
   team: "PHI",
   fatigue: 2,
   used:0,
   ability: "cancelOne",
   desc: "Cancel one run scored this inning."
},
{
   id: "031",
   first: "Dennis",
   last: "Evans",
   name: "Dennis Evans",
   number: 31,
   tier: 2,
   team: "MIA",
   fatigue: 1,
   used:0,
   ability:"setOne",
   desc:"Set one die to any value."
},
{
   id: "039",
   first: "Roger",
   last: "Quinn",
   name: "Roger Quinn",
   number: 39,
   tier: 3,
   team: "TOR",
   fatigue: 6,
   used:0,
   ability: "addD6",
   desc: "Add one die to the opponent's pool, then remove one die before resolving the inning."
},
{
   id: "040",
   first: "Micky",
   last: "Fisher",
   name: "Micky Fisher",
   number: 40,
   tier: 3,
   team: "DET",
   fatigue: 2,
   used:0,
   ability: "setOne",
   desc: "Set one die to any value."
},
{
   id: "041",
   first: "Danny",
   last: "O'Neill",
   name: "Danny O'Neill",
   number: 41,
   tier: 3,
   team: "CHC",
   fatigue: 4,
   used:0,
   ability: "adjustOne",
   desc: "Adjust one die up or down by one."
},
{
   id: "042",
   first: "Leroy",
   last: "Smith",
   name: "Leroy Smith",
   number: 42,
   tier: 3,
   team: "WSH",
   fatigue: 5,
   used:0,
   ability: "rerollSet",
   desc: "Reroll any subset of dice."
},
{
   id: "043",
   first: "Ricky",
   last: "Oliver",
   name: "Ricky Oliver",
   number: 43,
   tier: 3,
   team: "STL",
   fatigue: 3,
   used:0,
   ability: "cancelOne",
   desc: "Cancel one run scored this inning."
},
{
   id: "046",
   first: "Kanji",
   last: "Saito",
   name: "Kanji Saito",
   number: 46,
   tier: 3,
   team: "TB",
   fatigue: 1,
   used:0,
   ability: "cancelAll",
   desc: `Cancel all runs scored this inning. Fatigue tokens may not be removed during a game.`
},
{
   id: "047",
   first: "Luis",
   last: "Torres",
   name: "Luis Torres",
   number: 47,
   tier: 2,
   team: "CWS",
   fatigue: 5,
   used:0,
   ability:"addD10",
   desc: "Add the d10 to the opponent's pool, then remove one die before resolving the inning."
}]